# K?t n?i Microsoft SQL Server Express
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=payroll_db;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=123456

# T? ??ng ??ng b? b?ng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# H? tr? Unicode ti?ng Vi?t 100% trong SQL Server (ch?ng l?i d?u ?)
spring.jpa.properties.hibernate.use_nationalized_character_data=true
